import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Black Holdings-A path to the ambitious future",
  description: "Generated by create next app",
};

import ChartBackground from './ChartBackground';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="has-chart">
        {children}
      </body>
    </html>
  );
}
